// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDB2X6SIsKD6wMA39j_FLF-gJ544ltFy84',
    appId: '1:327340365335:web:d9eeab3b29b26843fb2e52',
    messagingSenderId: '327340365335',
    projectId: 'crudoperation2-b07ab',
    authDomain: 'crudoperation2-b07ab.firebaseapp.com',
    storageBucket: 'crudoperation2-b07ab.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAw2OUwADPMILOrSfDIXmkffjXX6y8tVsI',
    appId: '1:327340365335:android:dc14ba1a0cb32ff5fb2e52',
    messagingSenderId: '327340365335',
    projectId: 'crudoperation2-b07ab',
    storageBucket: 'crudoperation2-b07ab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDS8_eHvpHrvJdKCQJbGvJ6IzEwjis-Rng',
    appId: '1:327340365335:ios:3d055b3ff3b94408fb2e52',
    messagingSenderId: '327340365335',
    projectId: 'crudoperation2-b07ab',
    storageBucket: 'crudoperation2-b07ab.appspot.com',
    iosBundleId: 'com.example.crudOperation2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDS8_eHvpHrvJdKCQJbGvJ6IzEwjis-Rng',
    appId: '1:327340365335:ios:3d055b3ff3b94408fb2e52',
    messagingSenderId: '327340365335',
    projectId: 'crudoperation2-b07ab',
    storageBucket: 'crudoperation2-b07ab.appspot.com',
    iosBundleId: 'com.example.crudOperation2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDB2X6SIsKD6wMA39j_FLF-gJ544ltFy84',
    appId: '1:327340365335:web:ab6297aaa5e63de9fb2e52',
    messagingSenderId: '327340365335',
    projectId: 'crudoperation2-b07ab',
    authDomain: 'crudoperation2-b07ab.firebaseapp.com',
    storageBucket: 'crudoperation2-b07ab.appspot.com',
  );
}
